### ISSUE TITLE
concurrent USB devicss

### ISSUE THREAD

**Issue by orangecms** [fossasia/pslab-python#170] opened 2021-02-25 01:05 UTC
Cross-referenced from pslab-desktop:
https://github.com/fossasia/pslab-desktop/issues/673

Please have a look over there, an issue reported with multiple USB serial devices present.

**Comment by bessman** [comment] 2021-02-25 08:23
This is already possible by specifying the port name of the second device, e.g:

```python
import pslab
h1 = pslab.serial_handler.SerialHandler(port="/dev/ttyUSB0")
h2 = pslab.serial_handler.SerialHandler(port="/dev/ttyUSB1")
scope1 = pslab.Oscilloscope(h1)
scope2 = pslab.Oscilloscope(h2)
```

However, autodiscovery currently only picks up the first device. That's worth fixing.

**Comment by SwapnilSoni1999** [comment] 2021-02-27 23:19
So what is the expected behaviour?

**Comment by orangecms** [comment] 2021-02-28 00:34
Here's my suggestion:
Iterate over all USB devices, see if they respond with a PSLab name / version number, and in the desktop app, offer a list. The CLI could report that there are multiple devices available and ask to rerun the command with the device specified through an argument.
That is also the behvior of other tools, e.g., `flashrom`.

What do you think?

**Comment by bessman** [comment] 2021-02-28 09:14
That seems like a good solution.

**Comment by bessman** [comment] 2021-02-28 19:49
#173

**Comment by bessman** [comment] 2021-03-04 08:09
I'm closing this since #173 is merged. Let me know if you think the solution works for pslab-desktop.

**Closed by bessman** 2021-03-04 08:09 UTC

**Comment by orangecms** [comment] 2021-03-04 11:00
Sounds good, thank you so much! :)
